name             'fishnet'
maintainer       'Colin Shea'
maintainer_email 'colin@shea.at'
license          'all_rights'
description      'I know all about networking'
long_description 'Manages my network, around layer 5-6'
version          '0.3.2'

depends 'tinc'
depends 'ohai'
