name             'websites'
maintainer       'Colin Shea'
maintainer_email 'colin@shea.at'
license          'all_rights'
description      'Configuration for my variety of websites'
long_description 'nginx & apache configuration for my variety of websites and web apps'
version          '0.1.9'

depends 'nginx', '~> 2.7'
depends 'apache2', '~> 3.1'
