name             'feedbin'
maintainer       'Colin Shea'
maintainer_email 'colin@shea.at'
license          'all_rights'
description      'Installs/Configures feedbin, the feed reader'
long_description 'Installs/Configures feedbin server, fresher and camo image proxy'
version          '0.1.0'

depends 'postgresql'
depends 'redisio'
depends 'brightbox-ruby', '~> 1.2.0'
depends 'database'
depends 'nginx'
depends 'git'
