# only include the automatic updater for chef for a few distros. Notably,
# omnibus_updater doesn't work at all in Arch Linux, so avoid including it
# there.
if centos? || ubuntu? || debian? || rhel?
  include_recipe 'omnibus_updater::default'
end

one_week_ago = Time.now - 60*60*24*7
# There are a bunch of old reports generated by Chef's JSON file handler. Clean
# up all of them older than 1 week
Dir['/var/chef/reports/*.json'].each do |path|
  path_ctime = ::File.stat(path).ctime
  file path do
    action :delete
    backup false
    only_if { path_ctime < one_week_ago }
  end

  # break early so we don't call stat() on all the recent files, small
  # optimization
  break if path_ctime > one_week_ago
end
